apiVersion: v1
kind: Pod
metadata:
  name: app-js
  labels:
    name: app-js
spec:
  containers:
  - name: app-js
    image: appjs
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
    env:
      - name: USER_ID
        value: Marco
        # valueFrom:
        #   configMapKeyRef:
        #     name: appjs-config
        #     key: USER_ID_CONFIG
    #envFrom:
    #- configMapRef:
    #    name: appjs-config