apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
  labels:
    name: appjava-deploy
spec:
  selector:
    matchLabels:
      name: app-java
  replicas: 2
  template:
    metadata:
      labels:
        name: app-java
    spec:
      containers:
      - name: app-java
        image: appjava
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
