apiVersion: v1
kind: Pod
metadata:
  name: app-java
  labels:
    name: app-java
spec:
  containers:
  - name: app-java
    image: appjava
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
    # readinessProbe:
    #   httpGet:
    #     path: /email
    #     port: 8080
    #   initialDelaySeconds: 60
    #   periodSeconds: 60